# Twitter Bot Configuration

# API Configuration
api:
  google_cloud:
    credentials_path: "credentials/gcp-credentials.json"
    project_id: "twitterstoryagent"
  twitter:
    api_version: "2"
    rate_limit:
      max_requests: 50
      time_window: 900  # 15 minutes in seconds
  instagram:
    api_version: "v18.0"
    rate_limit:
      max_requests: 200
      time_window: 3600  # 1 hour in seconds
    features:
      - basic_display
      - graph_api
    permissions:
      - instagram_basic
      - pages_show_list
      - instagram_content_publish
      - instagram_manage_comments
    media_types:
      - image
      - carousel
      - story
    image_requirements:
      min_width: 1080
      min_height: 1080
      max_aspect_ratio: 1.91
      supported_formats:
        - jpeg
        - png
    caption:
      max_length: 2200
      hashtag_limit: 30
      default_hashtags:
        - solarpunk
        - sustainable
        - future
    webhooks:
      enabled: true
      verify_token: "your_webhook_verify_token"
      callback_url: "https://your-domain.com/webhook/instagram"
    insights:
      enabled: true
      metrics:
        - reach
        - engagement
        - impressions
    moderation:
      enabled: true
      auto_moderate_comments: true
      block_words: []
      require_approval: false

# Story Generation
story:
  max_length: 280  # Twitter character limit
  genres:
    - fantasy
    - sci-fi
    - mystery
    - humor
    - romance
  prompt_template: |
    Generate a creative one-sentence story in the {genre} genre.
    The story should be engaging and positively show people there is a better way to live.
    Include vivid imagery that can be translated into a visual.

# Image Generation
image:
  size: "1024x1024"
  style_presets:
    - photorealistic
    - watercolor
    - digital_art
    - pixel_art
  prompt_template: |
    Create a visually striking image based on this story: {story}
    Style: {style}
    The image should be suitable for social media and family-friendly.

# Scheduling
schedule:
  posting_interval: 4  # hours
  timezone: "UTC"
  allowed_hours:
    start: 8
    end: 22
  max_posts_per_day: 6

# Logging
logging:
  level: "INFO"
  file: "logs/bot.log"
  max_size: 10485760  # 10MB
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Content Filtering
content_filter:
  enabled: true
  inappropriate_words: []
  max_retries: 3
  cooldown_period: 300  # 5 minutes

# Monitoring
monitoring:
  enabled: true
  metrics_port: 9090
  alert_thresholds:
    error_rate: 0.1
    api_latency: 5000  # ms
    failed_posts: 3 