"""Image generation module using Imagen 2 API.

This module provides functionality for generating solarpunk images
that visualize the stories created with the story generation module.
"""

import os
import time
import logging
from pathlib import Path
from typing import Dict, List, Optional, Any, Tuple, Union
from dataclasses import dataclass
from src.ai_solarpunk.clients import openai_image_client
import asyncio
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Import the story generator to use its functionality
from src.story_generator import StoryGenerator, StoryParameters

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# Project root directory
PROJECT_ROOT = Path(__file__).parent.parent

# Create output directory if it doesn't exist
OUTPUT_DIR = PROJECT_ROOT / "output" / "images"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

@dataclass
class ImageParameters:
    """Parameters for image generation."""
    style: str = "digital-art"
    samples: int = 1
    add_watermark: bool = True
    # model_name is kept for compatibility but not used in OpenAI-only mode
    model_name: str = "gpt-image-1"

    def __post_init__(self) -> None:
        """Ensure parameters are valid."""
        # Validate samples
        if self.samples < 1 or self.samples > 4:
            self.samples = 1
        # Validate style
        valid_styles = ["digital-art", "watercolor", "stylized", "solarpunk-nouveau", "retro-futurism", "isometric"]
        if self.style not in valid_styles:
            self.style = "digital-art"

class ImageGenerator:
    """Generator for solarpunk images using OpenAI only."""
    def __init__(self) -> None:
        """Initialize the image generator (OpenAI only)."""
        logger.info("ImageGenerator configured to use OpenAI provider only.")

    def generate_image(
        self,
        prompt: str,
        setting: str,
        params: Optional[ImageParameters] = None,
        save_path: Optional[str] = None
    ) -> Tuple[List[Any], Dict[str, Any]]:
        """Generate images based on a prompt using OpenAI.
        
        Args:
            prompt: The prompt to visualize (should be generated by LLM extraction)
            setting: The setting of the story (urban, coastal, etc.)
            params: Parameters for image generation
            save_path: Optional path to save the image(s)
        Returns:
            Tuple of (list of PIL Image objects, metadata)
        """
        if params is None:
            params = ImageParameters()
        logger.info("Using OpenAI GPT Image 1 (DALL-E 3) model for image generation.")
        image_path = asyncio.run(openai_image_client.generate_image(
            prompt,
            output_dir=Path(save_path).parent if save_path else None,
            save_path=Path(save_path) if save_path else None
        ))
        metadata = {
            "model": "gpt-image-1",
            "style": params.style,
            "prompt": prompt,
            "setting": setting,
            "timestamp": time.time(),
            "provider": "openai-gpt-image-1"
        }
        return [image_path], metadata


def create_simple_test(style: str = "digital-art") -> None:
    """Create a simple test to verify the image generation functionality.
    
    This test mirrors the test_google_apis.py implementation to ensure 
    baseline functionality works.
    """
    import os
    use_openai = os.getenv("USE_OPENAI", "false").lower() == "true"
    try:
        logger.info("Running simple test with basic prompt...")
        test_prompt = "A solarpunk city with vertical gardens and solar panels"
        if use_openai:
            logger.info("[Test] Using OpenAI GPT Image 1 (DALL-E 3) for simple test.")
            from src.ai_solarpunk.clients import openai_image_client
            import asyncio
            image_path = asyncio.run(openai_image_client.generate_image(test_prompt))
            logger.info(f"[Test] OpenAI image saved to: {image_path}")
            print(f"\nTest image saved to: {image_path}")
            return True
        else:
            # Initialize the image generator
            image_generator = ImageGenerator()
            # Create the model directly following test_google_apis.py approach
            model = ImageGenerationModel.from_pretrained("imagen-3.0-generate-002")
            # Generate with minimal parameters
            logger.info(f"Generating test image with prompt: '{test_prompt}'")
            response = model.generate_images(
                prompt=test_prompt,
                number_of_images=1,
                add_watermark=True
            )
            # Verify response
            if response is not None:
                # The response is already an iterable of images
                # Save the first image (there should be only one)
                timestamp = int(time.time())
                save_path = str(OUTPUT_DIR / f"test_basic_{timestamp}.png")
                response[0].save(save_path)
                logger.info(f"Simple test successful! Image saved to {save_path}")
                print(f"\nTest image saved to: {save_path}")
                return True
            else:
                logger.error("Simple test failed: No image generated")
                return False
    except Exception as e:
        logger.error(f"Simple test failed with error: {str(e)}")
        return False


def generate_test_images() -> None:
    """Generate sample images from solarpunk stories for testing."""
    # First run a simple test to verify the API works
    if not create_simple_test():
        print("Basic image generation test failed. Cannot proceed with story-based images.")
        return
        
    print("\nBasic image generation test succeeded. Proceeding with story-based images...")
    
    # Initialize the generators
    story_generator = StoryGenerator()
    image_generator = ImageGenerator()
    
    # Create parameters for different types of stories and images
    settings = ["urban", "coastal", "forest", "desert", "rural"]
    themes_list = [
        ["renewable energy", "community gardens", "localized production"],
        ["ocean conservation", "floating communities", "tidal energy"],
        ["forest stewardship", "ecological monitoring", "natural architecture"],
        ["water conservation", "solar power", "desert greening"],
        ["sustainable agriculture", "community ownership", "appropriate technology"]
    ]
    
    # Image styles to test
    styles = ["digital-art", "watercolor", "stylized"]
    
    # Check if a specific setting and style was requested
    setting_input = sys.argv[1] if len(sys.argv) > 1 else "all"
    style_input = sys.argv[2] if len(sys.argv) > 2 else "digital-art"
    
    # Filter settings if specific one requested
    if setting_input != "all":
        if setting_input in settings:
            selected_indices = [settings.index(setting_input)]
        else:
            logger.error(f"Unknown setting: {setting_input}")
            return
    else:
        selected_indices = range(len(settings))
    
    # Filter styles if specific one requested
    if style_input not in styles:
        style_input = "digital-art"
    
    # Process each selected setting
    for i in selected_indices:
        setting = settings[i]
        themes = themes_list[i]
        
        try:
            # Generate a story
            logger.info(f"Generating story for {setting} setting...")
            story_params = StoryParameters(
                max_chars=280,
                themes=themes,
                setting=setting,
                ai_role="collaborative",
                tone="hopeful"
            )
            
            story, story_metadata = story_generator.generate_story(story_params)
            
            # Display the generated story
            print("\n" + "="*80)
            print(f"SOLARPUNK STORY - {setting.upper()} SETTING")
            print("="*80)
            print(story)
            print("-"*80)
            
            # Generate an image based on the story
            logger.info(f"Generating {style_input} image for {setting} setting...")
            image_params = ImageParameters(
                style=style_input,
                samples=1,
                add_watermark=True
            )
            
            # Create a timestamp-based filename
            timestamp = int(time.time())
            save_path = str(OUTPUT_DIR / f"{setting}_{style_input}_{timestamp}.png")
            
            # Generate and save the image
            images, image_metadata = image_generator.generate_image(
                story=story,
                setting=setting,
                params=image_params,
                save_path=save_path
            )
            
            print(f"Image generated and saved to: {save_path}")
            print(f"Image style: {image_metadata['style']}")
            print("="*80)
            
        except Exception as e:
            logger.error(f"Error processing {setting} setting: {str(e)}")


if __name__ == "__main__":
    import sys
    
    print("Solarpunk Image Generator - Testing Tool")
    print("========================================")
    print("Usage: uv run src/image_generator.py [setting] [style]")
    print("Available settings: urban, coastal, forest, desert, rural, all")
    print("Available styles: digital-art, watercolor, stylized, solarpunk-nouveau, retro-futurism, isometric")
    print("Default: all settings with digital-art style")
    
    generate_test_images() 